# Site settings
title: JING HUANG
SEOTitle: JingTalk博客
header-img: img/jing-home.png
email: jinghuang1130@yahoo.com
description: "Android,jingtalk,iOS,PM,MAC,huangjing"
keyword: "Android,jingtalk,iOS,PM,MAC,huangjing"
url: "https://jingtalk.github.io/"              # your host, for absolute URL
baseurl: ""                            # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: true
weibo_username:     JING_HUANG_






